javascript:
  - '**/*.js'
typescript:
  - '**/*.ts'
php:
  - '**/*.php'
html:
  - '**/*.html'
css:
  - '**/*.css'
python:
  - '**/*.py'
cpp:
  - '**/*.cpp'
  - '**/*.cxx'
  - '**/*.cc'
  - '**/*.cp'

'Type: Testing':
  - '**/tests/*'
  - '**/test/*'
  - '**/__tests__/*'

'Type: Documentation':
  - '**/*.md'

'Type: CI/CD':
  - '.github/workflows/*.yml'
  - '.circleci/*'
  - '.travis.yml'
